- hosts: all

  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted
      become: yes

  tasks:
    - name: "Roda: sudo apt-get update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia

    - name: "Instala pacotes"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx
        - nodejs

    - name: "clone projeto"
      ansible.builtin.git:
        repo: 'https://github.com/torneseumprogramador/nodejs-tdd-terraform-ansible'
        dest: /home/ubuntu/nodejs-tdd-terraform-ansible
        clone: yes
        update: yes

    - name: "fazendo build do projeto"
      shell: "cd /home/ubuntu/nodejs-tdd-terraform-ansible/itau-tdd-lab && npm install && nohup npm start &"
    
    - name: "Trocando nginx para ler a VPS"
      copy:
        src: "nginx/default"
        dest: "/etc/nginx/sites-available/default"
      become: yes
      notify:
        - "restart nginx"
